from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.colors import HexColor

def generate_pdf_report(title: str, body_text: str, output_path: str = "report.pdf"):
    """
    Generates a PDF report using reportlab.
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        name='TitleStyle',
        parent=styles['Heading1'],
        textColor=HexColor("#2C3E50"),
        spaceAfter=20,
        alignment=1 # Center
    )
    
    body_style = ParagraphStyle(
        name='BodyStyle',
        parent=styles['Normal'],
        fontSize=12,
        leading=16,
        spaceAfter=10
    )

    flowables = []

    # Title
    flowables.append(Paragraph(title, title_style))
    flowables.append(Spacer(1, 20))

    # Body (split by double newlines for basic paragraphs)
    for paragraph in body_text.split('\n\n'):
        if paragraph.strip():
            flowables.append(Paragraph(paragraph.strip(), body_style))
            flowables.append(Spacer(1, 10))

    doc.build(flowables)
    return output_path

if __name__ == "__main__":
    # Example usage
    sample_title = "Data Analysis Report"
    sample_body = (
        "Here is the summary of the dataset analysis.\n\n"
        "The total number of rows processed was 10,000, with an average rating of 4.5.\n\n"
        "Key insights have been successfully generated by the agent."
    )
    generate_pdf_report(sample_title, sample_body, "sample_report.pdf")
    print("Created sample_report.pdf")
